version: '2.1'
services:
  datacollector:
    build: sdc
    ports:
      - "18630:18630"
    environment:
      SDC_JAVA_OPTS: "-Xmx2g"
      STAGE_LIBS: "streamsets-datacollector-aws-lib,streamsets-datacollector-apache-kafka_0_10-lib,streamsets-datacollector-cassandra_3-lib,streamsets-datacollector-elasticsearch_5-lib,streamsets-datacollector-groovy_2_4-lib,streamsets-datacollector-redis-lib,streamsets-datacollector-jython_2_7-lib"
    volumes:
      - "./data/sdc:/data"
      - "./data/input:/var/data/"
  elasticsearch:
    image: elasticsearch:5.1.1
    environment:
      ES_JAVA_OPTS: "-Xms4g -Xmx4g"
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: kibana:5.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
  cassandra:
    image: cassandra:3.9
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
  redis:
    image: redis:3.2
    ports:
      - "6379:6379"
  redis_commander:
    image: osado/redis-commander
    ports:
      - "8081:8081"
    environment:
      WEB_USER: admin
      WEB_PASS: password
    depends_on:
      - redis
  # zookeeper:
  #   image: wurstmeister/zookeeper
  #   ports:
  #     - "2181:2181"
  # kafka:
  #   image: wurstmeister/kafka
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     # KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
  #     KAFKA_CREATE_TOPICS: "divvy-trip-input:1:1,divvy-trip-output:1:1"
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
