version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  producer:
    build: .
    entrypoint: ["java", "-cp", "/uber.jar", "io.kafkaspark.KafkaWordCountProducer"]
    command: ["kafka:9092", "test", "5", "10"]
  consumer:
    build: .
    command: ["kafka:9092", "test"]
  # streaming:
  #   image: rwhaling/kafka-spark-streaming
  #   entrypoint: ["java", "-cp", "/uber.jar", "io.kafkaspark.Main"]
  #   command: ["kafka:9092", "divvy-ride-load"]